services:
  app:
    build: .
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_started
    # image: docuseal/docuseal:latest
    ports:
      - 3000:3000
    volumes:
      - ./docuseal:/data/docuseal
    environment:
      - FORCE_SSL=false
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:pg123@host.docker.internal:5432/docuseal
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
  # postgres:
  #   image: postgres:18
  #   volumes:
  #     - './pg_data:/var/lib/postgresql/18/docker'
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: docuseal
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  caddy:
    image: caddy:latest
    command: caddy reverse-proxy --from $HOST --to app:3000
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy:/data/caddy
    environment:
      - HOST=${HOST}
